web:
  build: .
  command: bin/web
  environment:
    - CLIENT_ACCESS_SECRET
    - CLIENT_ACCESS_TOKEN
    - CLIENT_CONSUMER_KEY
    - CLIENT_CONSUMER_SECRET
    - CONSUMER_KEY
    - CONSUMER_SECRET
    - DATABASE_URL=postgres://postgres:password@postgres:5432/app
    - RACK_ENV=development
    - REDIS_URL=redis://redis:password@redis:6379/0
    - SECRET_KEY_BASE
    - SIDEKIQ_USERNAME
    - SIDEKIQ_PASSWORD
  links:
    - postgres
    - redis
  ports:
    - "80:3000"
    - "443:3000"
  volumes:
    - .:/app
sidekiq:
  build: .
  command: bin/sidekiq
  environment:
    - CLIENT_ACCESS_SECRET
    - CLIENT_ACCESS_TOKEN
    - CLIENT_CONSUMER_KEY
    - CLIENT_CONSUMER_SECRET
    - CONSUMER_KEY
    - CONSUMER_SECRET
    - DATABASE_URL=postgres://postgres:password@postgres:5432/app
    - RACK_ENV=development
    - REDIS_URL=redis://redis:password@redis:6379/0
    - SECRET_KEY_BASE
    - SIDEKIQ_USERNAME
    - SIDEKIQ_PASSWORD
  links:
    - postgres
    - redis
clock:
  build: .
  command: bin/clock
  environment:
    - DATABASE_URL=postgres://postgres:password@postgres:5432/app
    - REDIS_URL=redis://redis:password@redis:6379/0
  links:
    - postgres
    - redis
postgres:
  image: convox/postgres
redis:
  image: convox/redis
