web:
  build: .
  command: bin/web
  environment:
    - CLIENT_ACCESS_SECRET
    - CLIENT_ACCESS_TOKEN
    - CLIENT_CONSUMER_KEY
    - CLIENT_CONSUMER_SECRET
    - CONSUMER_KEY
    - CONSUMER_SECRET
    - RACK_ENV=development
    - SECRET_KEY_BASE
    - SIDEKIQ_USERNAME
    - SIDEKIQ_PASSWORD
  links:
    - database
    - redis
  ports:
    - "80:3000"
    - "443:3000"
  volumes:
    - .:/app
sidekiq:
  build: .
  command: bin/sidekiq
  environment:
    - CLIENT_ACCESS_SECRET
    - CLIENT_ACCESS_TOKEN
    - CLIENT_CONSUMER_KEY
    - CLIENT_CONSUMER_SECRET
    - CONSUMER_KEY
    - CONSUMER_SECRET
    - RACK_ENV=development
    - SECRET_KEY_BASE
    - SIDEKIQ_USERNAME
    - SIDEKIQ_PASSWORD
  links:
    - database
    - redis
clock:
  build: .
  command: bin/clock
  environment:
  links:
    - database
    - redis
database:
  image: convox/postgres
  ports:
    - 5432
redis:
  image: convox/redis
  ports:
    - 6379
